---
- name: "make backend dir"
  shell: mkdir /home/ubuntu/backend

- name: "send zipped backend file ==> "
  unarchive:
    src: ../../mybackend.tar.gz
    dest: /home/ubuntu

- name: "install backend"
  npm:
    path: /home/ubuntu/backend
    production: true
    global: true

- name: "start the app"
  shell: |
    cd /home/ubuntu/backend 
    pm2 stop all
    pm2 start npm -- run start